export const FoodActionTypes = {
  FETCH_FOODDATA_START: "FETCH_FOODDATA_START",
  FETCH_FOODDATA_SUCCESS: "FETCH_FOODDATA_SUCCESS",
  FETCH_FOODDATA_FAILURE: "FETCH_FOODDATA_FAILURE",
  UPDATE_IMAGE_URL: 'UPDATE_IMAGE_URL'
};
