export const UserActionTypes = {
  FETCH_USER_START: "FETCH_USER_START",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  USER_LOG_OUT: "USER_LOG_OUT",
  REGISTER_USER: "REGISTER_USER",
  SET_LOADING: "SET_LOADING:",
  TOGGLE_PROFILE_OPEN: "TOGGLE_PROFILE_OPEN"
};
